### ISSUE TITLE
Why Reader cannot read message when setting groupid?

### ISSUE THREAD

**Issue by afraidjpg** [segmentio/kafka-go#1098]
I used the following code to test: 

```go
func TestWriter(t *testing.T) {
	writer()
}

func TestReader(t *testing.T) {
	reader()
}

func reader() {
	r := kafka.NewReader(kafka.ReaderConfig{
		Brokers:     []string{"localhost:9092"},
		GroupID:     "group-A",     <---- comment out this line, and uncomment out r.SetOffset(0), It could receive message, why?
		Topic:       "topic-A",
		Partition:   0,
		MinBytes:    10e3, // 10KB
		MaxBytes:    10e6, // 10MB
		MaxWait:     time.Millisecond * 500,
		Logger:      kafka.LoggerFunc(logf),
		ErrorLogger: kafka.LoggerFunc(logf),
	})

	//r.SetOffset(0)
	for {
		m, err := r.ReadMessage(context.Background())
		if err != nil {
			fmt.Println(err)
			break
		}

		fmt.Printf("message at offset %d: %s = %s\n", m.Offset, string(m.Key), string(m.Value))
	}

	if err := r.Close(); err != nil {
		log.Fatal("failed to close reader:", err)
	}

	fmt.Println("close reader")
}

func writer() {
	w := &kafka.Writer{
		Addr:     kafka.TCP("localhost:9092"),
		Topic:    "topic-A",
		Balancer: &kafka.LeastBytes{},
	}

	t := time.Now().Format(time.DateTime)
	err := w.WriteMessages(context.Background(),
		kafka.Message{
			Value: []byte("send message at " + t),
		},
	)
	if err != nil {
		log.Fatal("failed to write messages:", err)
	}

	if err := w.Close(); err != nil {
		log.Fatal("failed to close writer:", err)
	}

	log.Println("close writer")
}

```

I started `TestReader` first and then run `TestWriter`, but the reader didn't ouput anything. 
output of console: 
```
=== RUN   TestReader
entering loop for consumer group, group-A

joined group group-A as member ___TestReader_in_kafka.test@zhaokundeMacBook-Pro.local (github.com/segmentio/kafka-go)-24891220-9e6c-4dff-a892-85f4851126de in generation 10
joinGroup succeeded for response, group-A.  generationID=10, memberID=___TestReader_in_kafka.test@zhaokundeMacBook-Pro.local (github.com/segmentio/kafka-go)-24891220-9e6c-4dff-a892-85f4851126de
Joined group group-A as member ___TestReader_in_kafka.test@zhaokundeMacBook-Pro.local (github.com/segmentio/kafka-go)-24891220-9e6c-4dff-a892-85f4851126de in generation 10
received empty assignments for group, group-A as member ___TestReader_in_kafka.test@zhaokundeMacBook-Pro.local (github.com/segmentio/kafka-go)-24891220-9e6c-4dff-a892-85f4851126de for generation 10
sync group finished for group, group-A
subscribed to topics and partitions: map[]
started heartbeat for group, group-A [3s]
started commit for group group-A


```

But if I comment out the GroupId, It could receive message normally

**Comment by afraidjpg** [comment]
I tried to restart kalka(in docker), then run the test, It can receive message at first time, but after I terminated test, and restart the test, It become unable to receive messages

**Comment by afraidjpg** [comment]
here is the output on not setting groupid:

```
=== RUN   TestReader
setting the offset of the kafka reader for partition 0 of topic-A from first offset to 0
initializing kafka reader for partition 0 of topic-A starting at offset 0
the kafka reader for partition 0 of topic-A is seeking to offset 0
looking up offset of kafka reader for partition 0 of topic-A: 0
no messages received from kafka within the allocated time for partition 0 of topic-A at offset 2]
message at offset 0:  = send message at 2023-03-15 16:19:44
message at offset 1:  = send message at 2023-03-15 16:23:53
no messages received from kafka within the allocated time for partition 0 of topic-A at offset 2
no messages received from kafka within the allocated time for partition 0 of topic-A at offset 2
no messages received from kafka within the allocated time for partition 0 of topic-A at offset 2
no messages received from kafka within the allocated time for partition 0 of topic-A at offset 2
no messages received from kafka within the allocated time for partition 0 of topic-A at offset 2
// ....
no messages received from kafka within the allocated time for partition 0 of topic-A at offset 2
no messages received from kafka within the allocated time for partition 0 of topic-A at offset 3
message at offset 2:  = send message at 2023-03-15 16:27:39. <-- send the message again here
no messages received from kafka within the allocated time for partition 0 of topic-A at offset 3
// ....
```

**Comment by afraidjpg** [comment]
system info:
MACOS 13.2.1
Apple M1 Pro. 

docker-compose.yml: 
```yaml

version: '3'
services:
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: always
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LOG_RETENTION_HOURS=6
    #volumes:
      #- ./kafka:/bitnami/kafka
    depends_on:
      - zookeeper

```
