### ISSUE TITLE
CPU is full on consumer

### ISSUE THREAD

**Issue by ltp217** [segmentio/kafka-go#1114]
when I use kafka-go v0.4.38, and kafka version is 2.4.1,
the producer is on other machine with other language, it may create about 8000 msgs per minute,
On the consumer machine, use kafka-go to consume messages, after a while, maybe 3 hours or longer time, the cpu is full to 100% . There is some strange thing: the cpu on the consumer machine is grow slowly to full. On the consumer side, only fetchMessage and commitMessage.
```
func main() {
	ctx := context.Background()
	c := NewKafkaConsumer(ctx)
	fmt.Printf("consumer topics:%+v\n", c.GetGroupTopics())
	for {
		msgs, err := c.FetchMessage(ctx)
		select {
		case <-ctx.Done():
			fmt.Println("ctx done")
			return
		default:
			if err != nil {
				fmt.Printf("kafka consumer err: %+v\n", err)
				return
			}
			time.Sleep(20 * time.Millisecond)
			if err = c.CommitMessages(ctx, msgs); err != nil {
				fmt.Println("commit msg err")
			}
			fmt.Printf("c msgs: %s\n", string(msgs.Value))
		}
	}
}
```

the config is :
```
kafka_consumer_config:
      brokers: "xxx:9092"
      topics: "test_topic"
      groupId: "test_group"
      startOffset: -1
      maxWait: 1
      maxAttempts: 3
      maxRollback: 5
      lagInterval: 30
      lagThreshold: 10
      commitInterval: 1
      queueCapacity: 100
```
and the other param in config is zero or nil.

the pprof is like:
![image](https://user-images.githubusercontent.com/16595000/231192561-faa4f840-2a55-4318-88ff-feab17a5d0e4.png)

![image](https://user-images.githubusercontent.com/16595000/231192909-65f13c04-9fbe-4bbd-8d1f-7c2d89f8ca4a.png)

![image](https://user-images.githubusercontent.com/16595000/231193589-e41fe30d-6a37-4d3f-a445-2a0111dd138c.png)

on the other hand, if the producer create less msg ,for example, 200 msgs per minute, it works well.

Is there any suggestions for me to deal with this scenes? 
thanks
