### ISSUE TITLE
Rebalancing the consumer via WatchPartitionChanges doesn't seem to work

### ISSUE THREAD

**Issue by simone** [segmentio/kafka-go#1134]
**Describe the bug**

> Rebalancing the consumer via WatchPartitionChanges doesn't seem to work as expected. By increasing the number of partitions the consumers in the group do not rebalancing each others to reassign the new partition to one of them. Only a restart of the consumers solve the issue. (workaround)

**Kafka Version**

> * What version(s) of Kafka are you testing against?
3.2.1 (Commit:b172a0a94f4ebb9f)
3.1.0 (Commit:37edeed0777bacb3)

> * What version of kafka-go are you using?
github.com/segmentio/kafka-go v0.4.40
github.com/segmentio/kafka-go v0.4.38

**To Reproduce**

> Resources to reproduce the behavior:
* create a topic with one partition "search-events"
* publish a message on it
* start the kafka-go consumer as described in the main
* alter the partitions number to 2 for the topic "search-events"

```yaml
---
# docker-compose.yaml
version: '3.7'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: always
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    restart: always
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
...
```

```go
package main

import (
    "github.com/segmentio/kafka-go"
)

func main() {
	reader := kafka.NewReader(kafka.ReaderConfig{
		Brokers:                []string{"kafka:9092"},
		Topic:                  "search-events",
		GroupID:                "search-service",
		MinBytes:               10e3, // 10KB
		MaxBytes:               10e6, // 10MB
		WatchPartitionChanges:  true,
		PartitionWatchInterval: 10 * time.Second,
	})
	defer reader.Close()
	for {
		m, err := reader.FetchMessage(context.Background())
		if err != nil {
			log.Fatal(err)
		}
		log.Printf("message at offset %d: %s = %s\n", m.Offset, string(m.Key), string(m.Value))
	}
}
```

**Expected Behavior**

> See a rebalancing on the consumer that take both the partitions

**Observed Behavior**

> The consumer remain connected only to the partition 0, the new partition 1 is not read by any consumers in the group
