### ISSUE TITLE
kafka.Conn.Broker() and kafka.Conn.Controller() return different Host value when there is one broker.

### ISSUE THREAD

**Issue by longyue0521** [segmentio/kafka-go#1217]
**Describe the bug**

> A clear and concise description of what the bug is.

kafka.Conn.Broker() and kafka.Conn.Controller() return different Host value when there is one broker.

**Kafka Version**

> * What version(s) of Kafka are you testing against?
> * What version of kafka-go are you using?

bitnami/kafka 3.6.0
kafka-go v0.4.44

**To Reproduce**

> Resources to reproduce the behavior:

copy from `Apache Kafka development setup example` section of https://hub.docker.com/r/bitnami/kafka

```yaml
---
# docker-compose.yaml
#
# Adding a docker-compose file will help the maintainers setup the environment
# to reproduce the issue.
#
# If one the docker-compose files available in the repository may be used,
# mentioning it is also a useful alternative.
version: "3"
services:
  kafka:
    image: 'bitnami/kafka:3.6.0'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
```

```go
package main

import (
    "fmt"
    "github.com/segmentio/kafka-go"
)

func main() {
         conn, _ := kafkago.Dial("tcp", "localhost:9092")

	broker := conn.Broker()
	fmt.Printf("%#v\n", broker)

	controllerBroker, _ := conn.Controller()
	fmt.Printf("%#v\n", controllerBroker)
}
```

**Expected Behavior**

> A clear and concise description of what you expected to happen.

I think they should be equal/same when there is only one broker

**Observed Behavior**

> A clear and concise description of the behavior you observed.

```
kafka.Broker{Host:"::1", Port:9092, ID:0, Rack:""}
kafka.Broker{Host:"4a22fb166591", Port:9092, ID:0, Rack:""}
```

**Additional Context**

> Add any other context about the problem here.

![image](https://github.com/segmentio/kafka-go/assets/6337745/294cea07-b717-4b44-bc05-4b37560e1c8f)

![image](https://github.com/segmentio/kafka-go/assets/6337745/b1ddcd27-5783-4194-b348-4480b15718a9)
