### ISSUE TITLE
Memory leak in writer

### ISSUE THREAD

**Issue by alzrck** [segmentio/kafka-go#1299]
**Describe the bug**

> A clear and concise description of what the bug is.

<img width="361" alt="image" src="https://github.com/segmentio/kafka-go/assets/2848295/27b1cd12-49b3-4078-aa8d-5fb2fb05e469">

We have exactly the same app running in 8 different clusters (one per city), 6 works ok, 2 has a leak that is shown in the image (add method piles up over and over).

Same kafka version (details below), same hardware layout, single topic, ~400 messages per second, each message is average 200 bytes.

**Kafka Version**

> * What version(s) of Kafka are you testing against?

binami kafka 3.6.0

> * What version of kafka-go are you using?

0.4.47

> Resources to reproduce the behavior:

```yaml
services:
  controller1:
    image: sb3rj02:5000/kafka:sb
    hostname: controller1
    volumes:
    - type: bind
      source: /mnt/${STORAGE}/data/kafka/${CITY_CODE}/c1
      target: /bitnami/kafka
    environment:
    - KAFKA_CFG_NODE_ID=1
    - KAFKA_KRAFT_CLUSTER_ID=m1Ze6AjGRwqarkcxJscgyQ
    - KAFKA_CFG_PROCESS_ROLES=controller
    - KAFKA_CFG_LISTENERS=CONTROLLER://controller1:9093
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@controller1:9093,2@controller2:9093,3@controller3:9093
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==sb0${CITY_CODE}01
    networks:
      - kfk

  controller2:
    image: sb3rj02:5000/kafka:sb
    hostname: controller2
    volumes:
    - type: bind
      source: /mnt/${STORAGE}/data/kafka/${CITY_CODE}/c2
      target: /bitnami/kafka
    environment:
    - KAFKA_CFG_NODE_ID=2
    - KAFKA_KRAFT_CLUSTER_ID=m1Ze6AjGRwqarkcxJscgyQ
    - KAFKA_CFG_PROCESS_ROLES=controller
    - KAFKA_CFG_LISTENERS=CONTROLLER://controller2:9093
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@controller1:9093,2@controller2:9093,3@controller3:9093
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==sb1${CITY_CODE}01
    networks:
      - kfk

  controller3:
    image: sb3rj02:5000/kafka:sb
    hostname: controller3
    volumes:
    - type: bind
      source: /mnt/${STORAGE}/data/kafka/${CITY_CODE}/c3
      target: /bitnami/kafka
    environment:
    - KAFKA_CFG_NODE_ID=3
    - KAFKA_KRAFT_CLUSTER_ID=m1Ze6AjGRwqarkcxJscgyQ
    - KAFKA_CFG_PROCESS_ROLES=controller
    - KAFKA_CFG_LISTENERS=CONTROLLER://controller3:9093
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@controller1:9093,2@controller2:9093,3@controller3:9093
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==sb2${CITY_CODE}02
    networks:
      - kfk

  broker1:
    image: sb3rj02:5000/kafka:sb
    hostname: broker1
    volumes:
    - type: bind
      source: /mnt/${STORAGE}/data/kafka/${CITY_CODE}/b1
      target: /bitnami/kafka
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    environment:
    - KAFKA_CFG_NODE_ID=21
    - KAFKA_KRAFT_CLUSTER_ID=m1Ze6AjGRwqarkcxJscgyQ
    - KAFKA_CFG_PROCESS_ROLES=broker
    - KAFKA_CFG_LISTENERS=INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
    - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://broker1:29092,EXTERNAL://sb1${CITY_CODE}01:9092
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@controller1:9093,2@controller2:9093,3@controller3:9093
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    extra_hosts:
      - sb1${CITY_CODE}01:${KAFKA1_IP}
      - sb2${CITY_CODE}02:${KAFKA2_IP}
      - sb3${CITY_CODE}02:${KAFKA3_IP}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==sb1${CITY_CODE}01
    networks:
      - kfk

  broker2:
    image: sb3rj02:5000/kafka:sb
    hostname: broker2
    volumes:
    - type: bind
      source: /mnt/${STORAGE}/data/kafka/${CITY_CODE}/b2
      target: /bitnami/kafka
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    environment:
    - KAFKA_CFG_NODE_ID=22
    - KAFKA_KRAFT_CLUSTER_ID=m1Ze6AjGRwqarkcxJscgyQ
    - KAFKA_CFG_PROCESS_ROLES=broker
    - KAFKA_CFG_LISTENERS=INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
    - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://broker2:29092,EXTERNAL://sb2${CITY_CODE}02:9092
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@controller1:9093,2@controller2:9093,3@controller3:9093
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    extra_hosts:
      - sb1${CITY_CODE}01:${KAFKA1_IP}
      - sb2${CITY_CODE}02:${KAFKA2_IP}
      - sb3${CITY_CODE}02:${KAFKA3_IP}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==sb2${CITY_CODE}02
    networks:
      - kfk

  broker3:
    image: sb3rj02:5000/kafka:sb
    hostname: broker3
    volumes:
    - type: bind
      source: /mnt/${STORAGE}/data/kafka/${CITY_CODE}/b3
      target: /bitnami/kafka
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    environment:
    - KAFKA_CFG_NODE_ID=23
    - KAFKA_KRAFT_CLUSTER_ID=m1Ze6AjGRwqarkcxJscgyQ
    - KAFKA_CFG_PROCESS_ROLES=broker
    - KAFKA_CFG_LISTENERS=INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
    - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://broker3:29092,EXTERNAL://sb3${CITY_CODE}02:9092
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@controller1:9093,2@controller2:9093,3@controller3:9093
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==sb3${CITY_CODE}02
    extra_hosts:
      - sb1${CITY_CODE}01:${KAFKA1_IP}
      - sb2${CITY_CODE}02:${KAFKA2_IP}
      - sb3${CITY_CODE}02:${KAFKA3_IP}
    networks:
      - kfk

networks:
  kfk:
    driver: overlay
```

```go
package kfk

import (
	"context"
	"strings"
	"time"

	"bricht.io/cbrcre/utils"
	"github.com/rs/zerolog/log"
	"github.com/segmentio/kafka-go"
)

func CallLogProducer(callLogChannel <-chan Event) {
	if utils.Cfg.KafkaBrokers == "" {
		log.Warn().Msg("KafkaBrokers not configured ... not starting thread")
		return
	}

	log_writer := kafka.Writer{
		Addr:      kafka.TCP(strings.Split(utils.Cfg.KafkaBrokers, ",")...),
		Topic:     "callLog",
		Transport: &kafka.Transport{IdleTimeout: 10 * time.Minute},
		Async:     true,
	}

	for {
		select {
		case callLog := <-callLogChannel:
			log_writer.WriteMessages(context.Background(), kafka.Message{Key: []byte(callLog.Key), Value: callLog.EventValue})
		}
	}
}
```

**Expected Behavior**

> A clear and concise description of what you expected to happen.

Keep the memory stable (as we get in the other running instances).

We tried to use different batch settings with no success (we are using async:true)

**Observed Behavior**

Memory is occupied slowly, it's not fast, GC sometimes deals with it, but it goes two steps ahead, GC step behind

**Additional Context**

If we turn off the feature (in our app) that uses the writer (so no more events are sent to the kfk cluster, memory remains stable)
