### ISSUE TITLE
`Can't assign requested address` error on MacOS using Docker

### ISSUE THREAD

**Issue by divmgl** [segmentio/kafka-go#226]
**Describe the bug**
```go
msg, err := reader.ReadMessage(context.Background())
```
throws this error on initial connection:
```
2019/03/09 14:45:43 dial tcp :0: connect: can't assign requested address
```
I'm running a single Kafka instance with Zookeeper using Docker on a MacOS machine.

**Kafka Version**
2.12

**To Reproduce**
```yml
version: '3.4'
services:
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    expose:
      - "2181"
```
Then run the code sample.
```go
func startReader(kafkaUri string) {
    config := kafka.ReaderConfig{
        Brokers:   []string{kafkaUri},
        Topic:     "mail",
        Partition: 0,
    }

    reader := kafka.NewReader(config)

    defer reader.Close()

    for {
        msg, err := reader.ReadMessage(context.Background())

        if err != nil {
            log.Fatal(err.Error())
        }

        fmt.Printf(
            "message at offset %d: %s = %s\n",
            msg.Offset,
            string(msg.Key),
            string(msg.Value),
        )
    }
}
```
**Expected behavior**
To consume messages without error.
