### ISSUE TITLE
Writer doesn't close properly

### ISSUE THREAD

**Issue by raviramanujam-okta** [segmentio/kafka-go#484]
**Describe the bug**
Calling `writer.Close()` never completes

**Kafka Version**
"2.2.1"

**To Reproduce**
- Create a writer
- Write a message
- Close the writer - never completes. 

**Expected behavior**
Expect `writer.Close()` to flush messages and close within a reasonable time limit

**Additional context**
This seems to be an issue on 0.3.7 and 0.3.8. We tried 0.4.1 but that has issues with TLS (https://github.com/segmentio/kafka-go/issues/477)

**Comment by dominicbarnes** [comment]
I did some testing locally to try and understand what might have happened here. Your ticket hasn't provided a lot of context on what your local setup was like, what code you ran, etc but I suspect it might have looked something like what I did.

I grabbed the example writer code from our readme, and adapted it into a `main.go` like this:

```go
package main

import (
	"context"
	"log"

	"github.com/segmentio/kafka-go"
)

func main() {
	// make a writer that produces to topic-A, using the least-bytes distribution
	w := kafka.NewWriter(kafka.WriterConfig{
		Brokers: []string{"localhost:9092"},
		Topic:   "topic-A",
		Balancer: &kafka.LeastBytes{},
	})

	w.WriteMessages(context.Background(),
		kafka.Message{
			Key:   []byte("Key-A"),
			Value: []byte("Hello World!"),
		},
		kafka.Message{
			Key:   []byte("Key-B"),
			Value: []byte("One!"),
		},
		kafka.Message{
			Key:   []byte("Key-C"),
			Value: []byte("Two!"),
		},
	)

	w.Close()

	fmt.Println("closed")
}
```

I'm using a `go.mod` which ensures we're pinned to v0.3.8

```
module issue-484

go 1.14

require github.com/segmentio/kafka-go v0.3.8
```

And lastly, I ran kafka with docker via `docker-compose.yml`:

```yaml
version: "3"
services:

  kafka:
    image: wurstmeister/kafka:0.11.0.1
    restart: on-failure:3
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_VERSION: '0.11.0.1'
      KAFKA_BROKER_ID: 1
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_ADVERTISED_HOST_NAME: 'localhost'
      KAFKA_ADVERTISED_PORT: '9092'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_MESSAGE_MAX_BYTES: 200000000

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
```

After starting up my docker-compose setup and running `main.go` things seemed to work ok. But upon inspecting the topic with kafkacat, I found no messages:

```sh
docker run -it --network=host edenhill/kafkacat:1.6.0 -b localhost:9092 -t topic-A
```

I added some error-handling to my `main.go`, which now looks like this:

```go
package main

import (
	"context"
	"log"

	"github.com/segmentio/kafka-go"
)

func main() {
	ctx := context.Background()

	w := kafka.NewWriter(kafka.WriterConfig{
		Brokers:  []string{"localhost:9092"},
		Topic:    "topic-A",
		Balancer: new(kafka.LeastBytes),
	})

	msg := kafka.Message{
		Key:   []byte("Key-A"),
		Value: []byte("Hello World!"),
	}

	if err := w.WriteMessages(ctx, msg); err != nil {
		log.Fatal("failed to write message", err)
	}

	if err := w.Close(); err != nil {
		log.Fatal("failed to close writer", err)
	}

	log.Print("closed")
}
```

When I tried again with the error-handling, I came across the following error:

> failed to write message [5] Leader Not Available: the cluster is in the middle of a leadership election and there is currently no leader for this partition and hence it is unavailable for writes

This turned out to explain in my case why the messages were not being written. I suspect if you took a similar process just trying to learn how to use this library, you may have encountered something similar to me.

The `WriteMessages` API blocks until the messages are successfully written, so it should either block/wait or return an error if it fails. In this example, the `Close` method would not get called until the operation had either failed or succeeded. The main exception here is if you've configured the writer to operate asynchronously, but that wasn't stated here.

I'm going to open a PR that updates our example code to include proper error-handling which may be able to make issues like this more clear, especially when making "hello world" scripts. Once that PR is merged, I will close this ticket as well. If you don't think I covered your actual problem (definitely possible!) then please follow up with additional details about your setup.
