### ISSUE TITLE
Consumer Group ignores/no read a partition

### ISSUE THREAD

**Issue by PacoDw** [segmentio/kafka-go#556]
**Describe the bug**
I created a basic consumer group to read a topic with 3 partitions:
```
  Producer WRITE =========> writer.go:734: writing 3331 messages to devices-messages-topic (partition: 0)
  Producer WRITE =========> writer.go:734: writing 3341 messages to devices-messages-topic (partition: 1)
  Producer WRITE =========> writer.go:734: writing 3328 messages to devices-messages-topic (partition: 2)
```

I made some variation in the reader configuration in order to find some issues but always is the same error :S

```go
	c := kafka.ReaderConfig{
		Brokers:  brokers,   // just one bbroker
		Topic:    topic,
                GroupID: "worker",
		MinBytes: 10e3, // 10KB
		MaxBytes: 10e6, // 10Mg
		MaxWait:     10 * time.Second,
		StartOffset: kafka.FirstOffset, // also I changed this but the same result
	}
```
Then When I run the consumer I noticed that it is not reading for one or two partition, in this case just for one, this is the log:

```
Decoder  Consumer READ ==========> reader.go:252: entering loop for consumer group, worker
Decoder  ConsumerERROR READ ====> consumergroup.go:638: Unable to establish connection to consumer group coordinator for group worker: [15] Group Coordinator Not Available: the broker returns this error code for group coordinator requests, offset commits, and most group management requests if the offsets topic has not yet been created, or if the group coordinator is not active
Decoder  ConsumerERROR READ ====> reader.go:263: [15] Group Coordinator Not Available: the broker returns this error code for group coordinator requests, offset commits, and most group management requests if the offsets topic has not yet been created, or if the group coordinator is not active
Decoder  Consumer READ ==========> consumergroup.go:794: joined group worker as member main@DESKTOP-UUO3E3V (github.com/segmentio/kafka-go)-d2b01fe7-3a5e-4675-9b28-5ae3a2599439 in generation 1
Decoder  Consumer READ ==========> consumergroup.go:854: selected as leader for group, worker
Decoder  Consumer READ ==========> consumergroup.go:882: using 'range' balancer to assign group, worker
Decoder  Consumer READ ==========> consumergroup.go:884: found member: main@DESKTOP-UUO3E3V (github.com/segmentio/kafka-go)-d2b01fe7-3a5e-4675-9b28-5ae3a2599439/[]byte(nil)
Decoder  Consumer READ ==========> consumergroup.go:884: found member: main@DESKTOP-UUO3E3V (github.com/segmentio/kafka-go)-0f740935-8aaf-4cc3-b3d1-291731450d6f/[]byte(nil)
Decoder  Consumer READ ==========> consumergroup.go:887: found topic/partition: devices-messages-topic/0
Decoder  Consumer READ ==========> consumergroup.go:887: found topic/partition: devices-messages-topic/2
Decoder  Consumer READ ==========> consumergroup.go:887: found topic/partition: devices-messages-topic/1
Decoder  Consumer READ ==========> consumergroup.go:808: assigned member/topic/partitions main@DESKTOP-UUO3E3V (github.com/segmentio/kafka-go)-0f740935-8aaf-4cc3-b3d1-291731450d6f/devices-messages-topic/[0]
Decoder  Consumer READ ==========> consumergroup.go:808: assigned member/topic/partitions main@DESKTOP-UUO3E3V (github.com/segmentio/kafka-go)-d2b01fe7-3a5e-4675-9b28-5ae3a2599439/devices-messages-topic/[2 1]
Decoder  Consumer READ ==========> consumergroup.go:815: joinGroup succeeded for response, worker.  generationID=1, memberID=main@DESKTOP-UUO3E3V (github.com/segmentio/kafka-go)-d2b01fe7-3a5e-4675-9b28-5ae3a2599439
Decoder  Consumer READ ==========> consumergroup.go:658: Joined group worker as member main@DESKTOP-UUO3E3V (github.com/segmentio/kafka-go)-d2b01fe7-3a5e-4675-9b28-5ae3a2599439 in generation 1
Decoder  Consumer READ ==========> consumergroup.go:981: Syncing 2 assignments for generation 1 as member main@DESKTOP-UUO3E3V (github.com/segmentio/kafka-go)-d2b01fe7-3a5e-4675-9b28-5ae3a2599439
Decoder  Consumer READ ==========> consumergroup.go:946: sync group finished for group, worker
Decoder  Consumer READ ==========> reader.go:101: subscribed to partitions: map[1:-2 2:-2]
Decoder  Consumer READ ==========> reader.go:1149: initializing kafka reader for partition 1 of devices-messages-topic starting at offset -2
Decoder  Consumer READ ==========> consumergroup.go:400: started heartbeat for group, worker [3s]
Decoder  Consumer READ ==========> reader.go:230: started commit for group worker
Decoder  Consumer READ ==========> reader.go:1149: initializing kafka reader for partition 2 of devices-messages-topic starting at offset -2
Decoder  Consumer READ ==========> reader.go:1329: the kafka reader for partition 2 of devices-messages-topic is seeking to offset 0
Decoder  Consumer READ ==========> reader.go:1329: the kafka reader for partition 1 of devices-messages-topic is seeking to offset 0
```
As you can se the consumer just reading for partition 1 and 2 but partition 0 is not readed

```
Decoder  Consumer READ ==========> reader.go:1231: no messages received from kafka within the allocated time for partition 1 of devices-messages-topic at offset 3341
Decoder  Consumer READ ==========> reader.go:1231: no messages received from kafka within the allocated time for partition 2 of devices-messages-topic at offset 3328
```
I used two different docker-compose file but the same error, these the different config:

```
---
version: "2"
services:
  zk1:
    image: confluentinc/cp-zookeeper:5.4.3
    ports:
      - "22181:22181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk1:22888:23888;zk2:32888:33888;zk3:42888:43888
  zk2:
    image: confluentinc/cp-zookeeper:5.4.3
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk1:22888:23888;zk2:32888:33888;zk3:42888:43888
  zk3:
    image: confluentinc/cp-zookeeper:5.4.3
    ports:
      - "42181:42181"
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk1:22888:23888;zk2:32888:33888;zk3:42888:43888
  kafka-1:
    image: confluentinc/cp-kafka:5.4.3
    ports:
      - "19092:19092"
    depends_on:
      - zk1
      - zk2
      - zk3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ${MY_IP}:22181,${MY_IP}:32181,${MY_IP}:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${MY_IP}:19092
  kafka-2:
    image: confluentinc/cp-kafka:5.4.3
    ports:
      - "29092:29092"
    depends_on:
      - zk1
      - zk2
      - zk3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: ${MY_IP}:22181,${MY_IP}:32181,${MY_IP}:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${MY_IP}:29092
  kafka-3:
    image: confluentinc/cp-kafka:5.4.3
    ports:
      - "39092:39092"
    depends_on:
      - zk1
      - zk2
      - zk3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: ${MY_IP}:22181,${MY_IP}:32181,${MY_IP}:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${MY_IP}:39092
```

Then I decided to change to a small config:

```
---
version: "2"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://${MY_IP}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
```

**Kafka Version**
I used the lastest version and 4.5.3
```
confluentinc/cp-zookeeper:latest // 4.5.3
confluentinc/cp-kafka:latest // 4.5.3
```

**To Reproduce**
- Create a Kafka cluster with one of the above configuration
- Create a topic with 3 partitions and fill it with 10_000 raws
- Later create a consumer passing a consumer group id 
- Then try to read the topic 
- And the error will show

**Expected behavior**
Read the N partitions using a consumer 

**Additional context**
One more thing that is too important, I created just one topic with one partition and the consumer reads all the messages succefully

Thank you so much :)
