### ISSUE TITLE
Goroutines leak in (*connPool).discover & (*conn).run

### ISSUE THREAD

**Issue by Antonboom** [segmentio/kafka-go#599]
### Describe the bug
**go.uber.org/goleak** founds unexpected goroutines in case of `kafka.(*Client).CreateTopics` error.

</details>

### Kafka Version
Confluent Platform 5.5.1 with **Kafka 2.5.1**.

### To Reproduce
**docker-compose.yaml**
```yaml
version: '3.7'

services:
  zookeeper:
    image: artifactory.sp.corp/docker/confluentinc/cp-zookeeper:5.5.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    expose:
      - "2181"

  kafka:
    image: artifactory.sp.corp/docker/confluentinc/cp-kafka:5.5.1
    depends_on:
      - zookeeper
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
```

**kafka_leak_test.go**
```go
package kafka

import (
	"context"
	"testing"
	"time"

	"github.com/segmentio/kafka-go"
	"go.uber.org/goleak"
)

func TestKafkaLeak(t *testing.T) {
	goleak.VerifyNone(t)
	defer goleak.VerifyNone(t)

	cli := &kafka.Client{
		Addr: kafka.TCP("127.0.0.1:9092"),
	}

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer func() {
		cancel()
		time.Sleep(time.Second) // Wait for shutdown inside kafka-go.
	}()

	_, err := cli.CreateTopics(ctx, &kafka.CreateTopicsRequest{
		Addr:   cli.Addr,
		Topics: []kafka.TopicConfig{{Topic: "topic"}},
	})
	if err != nil {
		t.Fatalf("unexpected error: %f", err)
	}
}
```

**Test output:**
```
=== RUN   TestKafkaLeak
    kafka_leak_test.go:31: unexpected error: &{%!f(string=kafka.(*Client).CreateTopics: dial tcp: lookup kafka: no such host) %!f(*net.OpError=&{dial tcp <nil> <nil> 0xc000020140})}
    leaks.go:78: found unexpected goroutines:
        [Goroutine 21 in state select, with github.com/segmentio/kafka-go.(*connPool).discover on top of the stack:
        goroutine 21 [select]:
        github.com/segmentio/kafka-go.(*connPool).discover(0xc000290180, 0x1855c20, 0xc00034b7c0, 0xc000362900)
        	/Users/a.telyshev/go/pkg/mod/github.com/segmentio/kafka-go@v0.4.8/transport.go:578 +0x365
        created by github.com/segmentio/kafka-go.(*Transport).grabPool
        	/Users/a.telyshev/go/pkg/mod/github.com/segmentio/kafka-go@v0.4.8/transport.go:254 +0x4ca
        
         Goroutine 6 in state chan receive, with github.com/segmentio/kafka-go.(*conn).run on top of the stack:
        goroutine 6 [chan receive]:
        github.com/segmentio/kafka-go.(*conn).run(0xc00007e0f0, 0xc000020080, 0xc000428000)
        	/Users/a.telyshev/go/pkg/mod/github.com/segmentio/kafka-go@v0.4.8/transport.go:1190 +0xa5
        created by github.com/segmentio/kafka-go.(*connGroup).connect
        	/Users/a.telyshev/go/pkg/mod/github.com/segmentio/kafka-go@v0.4.8/transport.go:1168 +0x910
        ]
--- FAIL: TestKafkaLeak (4.46s)
FAIL
```

### Expected behavior
No errors from goleak.

### Additional context
Why doesn't the client have a Close method?
