### ISSUE TITLE
failed to dial leader:dial 

### ISSUE THREAD

**Issue by crazyroller123456** [segmentio/kafka-go#670]
I'm trying to run the kafka demo given. Here's what I did.
```
kafka_message_consumer.go
package main

import (
	"context"
	"fmt"
	"log"
	"time"
	
	"github.com/segmentio/kafka-go"
)

func main() {
	// to consume messages
	topic := "my-topic"
	partition := 0
	
	conn, err := kafka.DialLeader(context.Background(), "tcp", "localhost:9092", topic, partition)
	if err != nil {
		log.Fatal("failed to dial leader:", err)
	}
	
	_ = conn.SetReadDeadline(time.Now().Add(10 * time.Second))
	batch := conn.ReadBatch(10e3, 1e6) // fetch 10KB min, 1MB max
	
	b := make([]byte, 10e3) // 10KB max per message
	for {
		_, err := batch.Read(b)
		if err != nil {
			break
		}
		fmt.Println(string(b))
	}
	
	if err := batch.Close(); err != nil {
		log.Fatal("failed to close batch:", err)
	}
	
	if err := conn.Close(); err != nil {
		log.Fatal("failed to close connection:", err)
	}
	fmt.Println("finished")
	log.Println("finished")
}

```
And the producer
```
kafka_message_producer.go
package main

import (
	"context"
	"fmt"
	"log"
	"time"
	
	"github.com/segmentio/kafka-go"
)

func main()  {
	// to produce messages
	topic := "topic"
	partition := 0
	
	conn, err := kafka.DialLeader(context.Background(), "tcp", "localhost:9092", topic, partition)
	if err != nil {
		fmt.Println("failed to dial leader:")
		log.Fatal("failed to dial leader:", err)
	}
	
	_ = conn.SetWriteDeadline(time.Now().Add(10 * time.Second))
	_, err = conn.WriteMessages(
		kafka.Message{Value: []byte("one!")},
		kafka.Message{Value: []byte("two!")},
		kafka.Message{Value: []byte("three!")},
	)
	if err != nil {
		fmt.Println("failed to write messages:")
		log.Fatal("failed to write messages:", err)
	}
	
	if err := conn.Close(); err != nil {
		fmt.Println("failed to close writer:")
		log.Fatal("failed to close writer:", err)
	}
	log.Printf("write successfully")
	fmt.Println("write successfully")
}
```
And a docker-compose file
```
version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

`docker-compose up -d`

Then I got this error message `failed to dial leader:dial tcp :0: connectex: The requested address is not valid in its context.`
