### ISSUE TITLE
error kafka write errors (1/1) when WriteMessages

### ISSUE THREAD

**Issue by swq123459** [segmentio/kafka-go#682]
**Describe the bug**
got error in test here : `kafka write errors (1/1)`
```
func TestCreateMqCafkaClient2(t *testing.T) {
	endPoint := "kafka:9092"
	w := &kafka.Writer{
		Addr:     kafka.TCP(endPoint),
		Topic:    "test",
		Balancer: &kafka.LeastBytes{},
	}

	err := w.WriteMessages(context.Background(),
		kafka.Message{
			Key:   []byte("Key-A"),
			Value: []byte("Hello World!"),
		},
	)
	if err != nil {
                // here is error
                // !!! kafka write errors (1/1)
		t.Errorf("failed to write messages:%v", err)
	}

}
```
kafka-go version: v0.4.16
**Kafka Version**
What version(s) of Kafka are you testing against?
```yaml
version: '3'
services:
  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
        - 2181:2181
```
**To Reproduce**
Steps to reproduce the behavior.  Bonus points for a code sample.

**Expected behavior**

**Additional context**
