### ISSUE TITLE
Unknown Topic Or Partition error, even though the topic should be created automatically

### ISSUE THREAD

**Issue by tim-hilt** [segmentio/kafka-go#683]
**Describe the bug**

When publishing a message, I get `Unknown Topic Or Partition: the request is for a topic or partition that does not exist on this broker`, event though it [should create the message by default, as far as I understand the `README.md`](https://github.com/segmentio/kafka-go#to-create-topics).

It worked before, when I was using the exact same setup on NixOS (until I switched to Arch Linux yesterday).

**Kafka Version**

Latest [docker-image from confluentinc](https://hub.docker.com/r/confluentinc/cp-kafka) (should be 2.7.1 if it's the latest official release from their GitHub, as of today)

**To Reproduce**

Start Kafka using the following `docker-compose.yaml`:

``` yaml
version: "3.3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
```

execute the following commands:

``` shell
docker-compose -f "FILE UNDER WHICH YOU'VE STORED THE ABOVE" up -d
mkdir tmp
cd tmp
go mod init example.com/tmp
go get -u github.com/segmentio/kafka-go
vim main.go
```

Fill `main.go` with the following lines:

``` go
package main

import (
	"context"

	"github.com/segmentio/kafka-go"
)

func main() {
	w := &kafka.Writer{
		Addr:  kafka.TCP("localhost:29092"),
		Topic: "hello",
	}

	err := w.WriteMessages(context.Background(), kafka.Message{
		Key:   []byte("hello"),
		Value: []byte("hello!"),
	})

	if err != nil {
		panic(err)
	}
}
```

Run `main.go`

``` shell
go run main.go
```

The output was the following for me:

``` shell
panic: [3] Unknown Topic Or Partition: the request is for a topic or partition that does not exist on this broker

goroutine 1 [running]:
main.main()
        /home/tim/tmp/main.go:21 +0x265
exit status 2
```

**Expected behavior**

The message should be published, even though the topic doesn't exist yet.

**Additional context**

``` shell
❯ uname -a
Linux t14s 5.12.10-arch1-1 #1 SMP PREEMPT Thu, 10 Jun 2021 16:34:50 +0000 x86_64 GNU/Linux
```

**Comment by tim-hilt** [comment]
I installed Kubuntu 21.04 to try out if the issue also exists on an Ubuntu-system. Turns out: Yes, still getting the same errors as above after applying the same commands.

``` shell
❯ uname -a
Linux t14s 5.11.0-18-generic #19-Ubuntu SMP Fri May 7 14:22:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by tim-hilt** [comment]
I also played around with the versions of the kafka- and zookeeper-images used in the `docker-compose.yaml`. Relaxing the versions to 5.4.4 doesn't change the behavior.

Note, that I have similar issues, when I use `kafkacat` and try to subscribe to a topic, that doesn't exist yet

**Comment by Hellysonrp** [comment]
I just tested this and I noticed that the topic is created if `kafka.DialLeader` is used to initialize the connection instead of directly using `kafka.Writer`.
Adding the following code to the beginning of your `main.go`, just to initialize the topic, "fixes" the issue:
```go
	conn, err := kafka.DialLeader(context.Background(), "tcp", "localhost:29092", "hello", 0)
	if err != nil {
		panic(err)
	}
	// close the connection because we won't be using it
	conn.Close()
```
This is not a good solution, I wouldn't even consider it as a solution to be honest, but can be used as a workaround if needed.

**Comment by tim-hilt** [comment]
Thanks for the reply and the workaround! Glad I'm not the only one experiencing this.

Is this an issue that will be fixed or should we just live with the workaround? Did you also notice any other tools/libs that showed similar behavior?

**Comment by tim-hilt** [comment]
I tried it again; this time using the wurstmeister-kafka-images. This is my `docker-compose.yml`:

``` yaml
version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:29092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "foo:1:1,bar:1:1"
```
the workaround with `KAFKA_CREATE_TOPICS` works, so the only thing that isn't working is auto-creation of topics.
