### ISSUE TITLE
"Unknown Topic Or Partition" error when requesting topics using TLS and SASL

### ISSUE THREAD

**Issue by benmathews** [segmentio/kafka-go#687]
**Describe the bug**
Getting a list of topics via client.Metadata works against an unencrypted port. But when encrypted with TLS and authenticated with SASL, it fails.

**Versions**
Kafka 2.8
Kafka-go: git hash of 27f7e6613085 (currently head)

**To Reproduce**
Using the strimzi operator I created a kafka cluster with these listeners

```yaml
      - authentication:
          type: scram-sha-512
        name: tls
        port: 9093
        tls: true
        type: internal
      - name: plain
        port: 9095
        tls: false
        type: internal
```
I can dig out the Kafka config this generates if needed.

I wrote a working test that goes through the plain listener.

```go
import (
	"context"
	"net"
	"testing"

	"github.com/segmentio/kafka-go"
	"github.com/segmentio/kafka-go/topics"
)

func TestKafkaSubscriber_GetTopics_plain(t *testing.T) {
	client := kafka.Client{
		Addr: kafka.TCP("....:9095"),
	}
	topicsSlice, err := topics.List(context.Background(), &client)
	if err != nil {
		t.Fatal(err)
	}
	if len(topicsSlice) < 10 {
		t.Fail()
	}
	t.Log(topicsSlice)
}
```

Then another failing test that goes through the TLS/SASL port

```go
func TestKafkaSubscriber_GetTopics_encrypted(t *testing.T) {
	broker := ".....:9093"

	saslMechanism := getSaslMechanism("....", "....")
	tlsConfig := getTlsConfig(".....")

	dialer := &kafka.Dialer{
		TLS:           tlsConfig,
		SASLMechanism: saslMechanism,
	}

	client := kafka.Client{
		Addr: kafka.TCP(broker),
		Transport: &kafka.Transport{
			Dial: func(ctx context.Context, network string, address string) (net.Conn, error) {
				return dialer.DialContext(ctx, "tcp", broker)
			},
		},
	}
	topicsSlice, err := topics.List(context.Background(), &client)
	if err != nil {
		t.Fatal(err) # Source of error
	}
	if len(topicsSlice) < 10 {
		t.Fail()
	}
	t.Log(topicsSlice)
}
```

This returns 

```
--- FAIL: TestKafkaSubscriber_GetTopics_encrypted (0.14s)
    /home/ben/vivint/pea/pubsub/kafka_subscriber_test.go:49: kafka.(*Client).Metadata: [3] Unknown Topic Or Partition: the request is for a topic or partition that does not exist on this broker
```

**Expected behavior**
topics.List and client.Metadata should work with TLS and SASL.

**Comment by Hellysonrp** [comment]
Probably related to #683

**Comment by benmathews** [comment]
@Hellysonrp why do you think this issue is related to #683? The topics are pre-created (weeks ago). I'm not asking for a particular one, just the list. So even if there were new ones, this should still report something. And finally, the first test through a plain port works. It is just when secured with TLS and SASL that it fails.

**Comment by Hellysonrp** [comment]
That's why I said 'probably'.
I just wanted to link the issues.
My line of thought was something like 'when calling this function, something is not being added to the connection, like the problem in #683'.
If it's not related, then it's not related, and I made a mistake.
Sorry if this caused any trouble :no_mouth:

**Comment by xdsxc** [comment]
I ran your second example locally but without the SASL mechanism and it still returns an error.

It seems like that the `kafka.Transport` is meant for use with the `kafka.Reader` and `kafka.Writer` types (based on[ this comment](https://github.com/segmentio/kafka-go/blob/711387657efffcd9af516d7853cebcdf39688d57/transport.go#L55-L56)). 

By default, the Kafka client uses the standard `net.DefaultTransport` if none is specified, which implies to me that it is meant to handle raw TCP connections instead of the higher level Kafka connections.

With that said, that still doesn't give you a good solution to list topics using SASL authenticated connections - I'll see if I can find something that'll work for that.

**Comment by xdsxc** [comment]
Apologies for the delay! Can you try this example?

```
	saslMechanism := getSaslMechanism("......")
	tlsConfig := getTLSConfig("......")

	client := kafka.Client{
		Addr: kafka.TCP(saslSSLAddr),
		Transport: &kafka.Transport{
			SASL: saslMechanism,
			TLS: tlsConfig,
		},
	}

	topicsSlice, err := topics.List(context.Background(), &client)
```

**Comment by benmathews** [comment]
I was on vacation, so my response is delayed. Thank you for looking at this.

While not identical, my code's essence is the same and it didn't work. 

```
&kafka.Client{
			Addr: kafka.TCP(broker),
			Transport: &kafka.Transport{
				ClientID: "pea",
				TLS:      getTlsConfig(cfg.CaRootCertFile),
				SASL:     getSaslMechanism(cfg.User, cfg.Password),
			},
		},
```

```
topicsList, err := topics.ListRe(context.TODO(), sub.client, re)
```

**Comment by rhansen2** [comment]
Hi @benmathews, I've been trying to reproduce this issue but I've been unable to thus far. My kafka cluster is set-up using the strimzi operator with the following config 
```yaml
    listeners:
      - authentication:
          type: scram-sha-512
        name: tls
        port: 9093
        tls: true
        type: internal
      - name: plain
        port: 9095
        tls: false
        type: internal
```
And have not had any errors when listing topics. 

One thing I notice about your failing test is 
```go
	client := kafka.Client{
		Addr: kafka.TCP(broker),
		Transport: &kafka.Transport{
			Dial: func(ctx context.Context, network string, address string) (net.Conn, error) {
				return dialer.DialContext(ctx, "tcp", broker) // <--- This line is always dialing the same broker instead of the address passed in to Dial
			},
		},
	}
```

If you're still having this issue could you try updating that line to dial the address passed in?

If that doesn't do it is there any other info you could provide to help me reproduce this?

Below is the full yaml of the resources I'm creating which is mostly taken from the strimzi quickstart examples.

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.8.0
    replicas: 1
    listeners:
      - authentication:
          type: scram-sha-512
        name: tls
        port: 9093
        tls: true
        type: internal
      - name: plain
        port: 9095
        tls: false
        type: internal        
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: kafka-scram-client-credentials
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512

```

**Comment by manyasi06** [comment]
@rhansen2 what does your client look like by chance?

**Comment by rhansen2** [comment]
@manyasi06 My full test program is:

```go
func main() {
	ca, err := os.Open("./ca.crt")
	if err != nil {
		panic(err)
	}
	cab, err := ioutil.ReadAll(ca)
	if err != nil {
		panic(err)
	}

	caCertPool := x509.NewCertPool()
	caCertPool.AppendCertsFromPEM(cab)

	config := &tls.Config{
		RootCAs: caCertPool,
	}

	mechanism, err := scram.Mechanism(scram.SHA512, "kafka-scram-client-credentials", "<redacted>")
	if err != nil {
		log.Fatal("Some scram err", err)
	}
	dialer := kafka.Dialer{
		TLS:           config,
		SASLMechanism: mechanism,
	}

	client := kafka.Client{
		Addr: kafka.TCP("my-cluster-kafka-bootstrap:9093"),

		Transport: &kafka.Transport{
			Dial: func(ctx context.Context, network string, address string) (net.Conn, error) {
				return dialer.DialContext(ctx, network, address)
			},
		},
	}
	ctx, cancel := context.WithTimeout(context.Background(), time.Second*10)
	topics, err := topics.List(ctx, &client)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Topics %+v\n", topics)
	cancel()

	groupID := "test-group-id"
	r := kafka.NewReader(kafka.ReaderConfig{
		Brokers:        []string{"my-cluster-kafka-bootstrap:9093"},
		GroupID:        groupID,
		Topic:          "my-topic",
		MaxBytes:       10e6, // 10MB
		MaxWait:        1 * time.Second,
		CommitInterval: time.Second,
		Dialer:         &dialer,
	})

	go func() {
		log.Println("starting producer")
		writer := kafka.NewWriter(kafka.WriterConfig{
			Brokers:      []string{"my-cluster-kafka-bootstrap:9093"},
			Topic:        "my-topic",
			Dialer:       &dialer,
			RequiredAcks: int(kafka.RequireAll),
		})
		for {
			<-time.After(time.Second * 3)
			ctx, cancel := context.WithTimeout(context.Background(), time.Second*10)
			err := writer.WriteMessages(ctx, kafka.Message{
				Key:   []byte("key" + strconv.Itoa(int(rand.Int63()))),
				Value: []byte("value" + strconv.Itoa(int(rand.Int63()))),
			})
			cancel()
			if err != nil {
				log.Println("produce ", err)
				continue
			}
			log.Println("Produced message")
		}
	}()

	for {
		ctx, cancel = context.WithTimeout(context.Background(), time.Second*10)
		d, err := r.ReadMessage(ctx)
		cancel()
		if err != nil {
			log.Println("Error reading message from Kafka", err)
		}
		log.Printf("message at topic:%v partition:%v offset:%v key:%v value:%v\n",
			d.Topic, d.Partition, d.Offset, string(d.Key), string(d.Value))
	}
}
```

**Comment by manyasi06** [comment]
@rhansen2 the only difference I think between our deployments is the authorizer setup.  In my previous deployment I end up defining the actual authorizer in my strimzi deployment.

```
authorization:
    type: keycloak
    superUsers:
      - admin
      - CN=go-client-shell
      - internalUser
     clientId: kafka-broker
     delegateToKafkaAcls: true
     disableTlsHostnameVerification: true
     grantsRefreshPoolSize: 5
     grantsRefreshPeriodSeconds: 60
     tokenEndpointUri: https://keycloak:8443/auth/realms/master/protocol/openid-connect/token
     tlsTrustedCertificates:
       - secretName: ca-truststore
         certificate: ca.crt
```

If I don't define the authorizer in strimzi than I am able to authenticate fine like you did above.
