### ISSUE TITLE
SASL scram and ssl not working properly

### ISSUE THREAD

**Issue by manyasi06** [segmentio/kafka-go#731]
**Describe the bug**

Currently have SASL and SSL setup for kafka configuration, but unable to connect to kafka cluster

```
kafka:
  replica: 3
  authorization:
    type: keycloak
    superUsers:
      - admin
      - CN=go-client-shell
      - internalUser
     clientId: kafka-broker
     delegateToKafkaAcls: true
     disableTlsHostnameVerification: true
     grantsRefreshPoolSize: 5
     grantsRefreshPeriodSeconds: 60
     tokenEndpointUri: https://keycloak:8443/auth/realms/master/protocol/openid-connect/token
     tlsTrustedCertificates:
       - secretName: ca-truststore
         certificate: ca.crt
  resources:
    limits:
      cpu: 2
      memory: 2Gi 
    requests:
      cpu: 2
      memory: 2Gi 
  storage:
    type: persistent-claim
    size: 100Gi
    deleteClaim: false
    class: standard
  logging:
    type: inline
    logger:
      kafka.root.logger.level: "TRACE" 
  listeners:
     - name: plain
       port: 9092
       type: internal
       tls: false
     - name: tls 
       port: 9093
       type: internal
       tls: true
     - name: external
       port: 9094
       type: internal
       tls: true
       authentication:
         type: oauth
         validIssuerUri: https://keycloak:8443/auth/realms/master
         jwksEndpointUri: https://keycloak:8443/auth/realms/master/protocol/openid-connect/certs
         userNameClaim: preferred_username
         maxSecondsWithoutReauthentication: 3600
         tlsTrustedCertificates:
           - secretName: ca-truststore
             certificate: ca.crt
         disableTlsHostnameVerification: true
     - name: saslplain
       port: 9095
       type: internal
       tls: true
       authentication:
         type: scram-sha-512
```

When connecting to Kafka I receive the following error:
```
kafka reader: entering loop for consumer group, testgrp
kafka reader: Unable to establish connection to consumer group coordinator for group testgrp: EOF
kafka reader: EOF
kafka reader: Unable to establish connection to consumer group coordinator for group testgrp: EOF
kafka reader: EOF
kafka reader: Unable to establish connection to consumer group coordinator for group testgrp: EOF
kafka reader: EOF
```

**Kafka Version**
What version(s) of Kafka are you testing against?
Kafka version 2.7.0

**To Reproduce**
Steps to reproduce the behavior.  Bonus points for a code sample.
Setup kafka broker with kafka configuration with ssl and port to authenicate using sasl-scram.  Works fine when just doing scram by itself but when adding ssl I get the error with EOF.

```
func NewTLSConfig(clientCertFile, clientKeyFile, caCertFile string) (*tls.Config, error) {
	tlsConfig := tls.Config{}
	// Load client cert
	cert, err := tls.LoadX509KeyPair(clientCertFile, clientKeyFile)
	if err != nil {
		return &tlsConfig, err
	}
	tlsConfig.Certificates = []tls.Certificate{cert}

	// Load CA cert
	caCert, err := ioutil.ReadFile(caCertFile)
	if err != nil {
		return &tlsConfig, err
	}
	caCertPool := x509.NewCertPool()
	caCertPool.AppendCertsFromPEM(caCert)
	tlsConfig.RootCAs = caCertPool
	tlsConfig.InsecureSkipVerify = true

	//tlsConfig.BuildNameToCertificate()
	return &tlsConfig, err

}

func doSaslScram() {
        bootstrapServer := getEnvVariable("BOOTSTRAP_SERVER")
        tlsConfig, err := NewTLSConfig("./user.crt", "./user.key", "./ca.crt")
        if err != nil {
                log.Fatal("Some cert err")
        }
        mechanism, err := scram.Mechanism(scram.SHA512, "my-user", "somepass")
        if err != nil {
                log.Fatal("Some scram err")
        }
        l := log.New(os.Stdout, "kafka reader: ", 0)
        dialer := &kafka.Dialer{
                Timeout:       10 * time.Second,
                DualStack:     true,
                TLS:           tlsConfig,
                SASLMechanism: mechanism,
        }   
        // make a new reader that consumes from topic-A
        r := kafka.NewReader(kafka.ReaderConfig{
                Brokers:     []string{bootstrapServer},
                GroupID:     "testgrp",
                Topic:       "a-topic",
                Dialer:      dialer,
                Logger:      l,  
                ErrorLogger: l,
        })  

        for {
                m, err := r.ReadMessage(context.Background())
                if err != nil {
                        break
                }   
                fmt.Printf("message at topic/partition/offset %v/%v/%v: %s = %s\n", m.Topic, m.Partition, m.Offset, string(m.Key), string(m.Value))
        }   

        if err := r.Close(); err != nil {
                log.Fatal("failed to close reader:", err)
        }   
}
```

Current Error:
```
kafka reader: entering loop for consumer group, testgrp
kafka reader: Unable to establish connection to consumer group coordinator for group testgrp: EOF
kafka reader: EOF
```

**Expected behavior**
Should be able to connect when doing sasl and scram with kafka reader
