### ISSUE TITLE
Reader never retrieve messages when the topic is empty at started

### ISSUE THREAD

**Issue by darienhf** [segmentio/kafka-go#759]
**Describe the bug**
Reader gets stuck and never reads messages when the topic is recently created or it is empty at the time the reader start.

**Kafka Version**
2.4.1

**To Reproduce**
I have the following docker-compose.yml

```
version: '3'
services:
  kafka:
    #    image: debezium/kafka:1.6
    image: wurstmeister/kafka:2.12-2.4.1
    container_name: kafka-segmentio-example-kafka
    restart: on-failure:3
    links:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_VERSION: '2.4.1'
      KAFKA_BROKER_ID: '1'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_ADVERTISED_HOST_NAME: 'localhost'
      KAFKA_ADVERTISED_PORT: '9092'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_MESSAGE_MAX_BYTES: '200000000'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,SASL_PLAINTEXT://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092,SASL_PLAINTEXT://localhost:9093'
      KAFKA_SASL_ENABLED_MECHANISMS: 'PLAIN,SCRAM-SHA-256,SCRAM-SHA-512'
      KAFKA_OPTS: "-Djava.security.auth.login.config=/opt/kafka/config/kafka_server_jaas.conf"
      CUSTOM_INIT_SCRIPT: |-
        echo -e 'KafkaServer {\norg.apache.kafka.common.security.scram.ScramLoginModule required\n username="adminscram"\n password="admin-secret";\n org.apache.kafka.common.security.plain.PlainLoginModule required\n username="adminplain"\n password="admin-secret"\n user_adminplain="admin-secret";\n  };' > /opt/kafka/config/kafka_server_jaas.conf;
        /opt/kafka/bin/kafka-configs.sh --zookeeper zookeeper:2181 --alter --add-config 'SCRAM-SHA-256=[password=admin-secret-256],SCRAM-SHA-512=[password=admin-secret-512]' --entity-type users --entity-name adminscram
  zookeeper:
    image: debezium/zookeeper:1.6
    container_name: customer-benefits-service-zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
```

with the following main.go

```
package main

import (
	"context"
	"fmt"
	"log"
	"net"
	"os"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/gofrs/uuid"
	kafka "github.com/segmentio/kafka-go"
)

func getKafkaReader(kafkaURL, topic, groupID string) *kafka.Reader {
	brokers := strings.Split(kafkaURL, ",")

	return kafka.NewReader(kafka.ReaderConfig{
		Brokers:  brokers,
		GroupID:  groupID,
		Topic:    topic,
		MinBytes: 10e3, // 10KB
		MaxBytes: 10e6, // 10MB
		StartOffset: kafka.LastOffset,
	})
}

func createTopic(kafkaURL, topic string) error {
	conn, err := kafka.Dial("tcp", kafkaURL)
	if err != nil {
		return err
	}
	defer conn.Close()

	controller, err := conn.Controller()
	if err != nil {
		return err
	}
	var controllerConn *kafka.Conn
	controllerConn, err = kafka.Dial("tcp", net.JoinHostPort(controller.Host, strconv.Itoa(controller.Port)))
	if err != nil {
		return err
	}
	defer controllerConn.Close()


	topicConfigs := []kafka.TopicConfig{
		{
			Topic:             topic,
			NumPartitions:     1,
			ReplicationFactor: 1,
		},
	}

	err = controllerConn.CreateTopics(topicConfigs...)
	if err != nil {
		return err
	}

	return nil
}

func getKafkaWriter(kafkaURL string) *kafka.Writer {
	return &kafka.Writer{
		Addr:     kafka.TCP(kafkaURL),
		// NOTE: When Topic is not defined here, each Message must define it instead.
		Balancer: &kafka.LeastBytes{},
		RequiredAcks: kafka.RequireOne,
	}
}

func main()  {
	// get kafka reader using environment variables.
	kafkaURL := os.Getenv("KAFKA_DSN") // localhost:9092
	topic := "events"
	groupID := "events-group-id"

	var wg sync.WaitGroup

	err := createTopic(kafkaURL, topic)
	if err != nil {
		log.Fatalln(err)
	}

	reader := getKafkaReader(kafkaURL, topic, groupID)
	defer reader.Close()

	wg.Add(1)

	go func() {
		defer wg.Done()

		fmt.Println("start consuming ... !!")
		for {
			m, err := reader.ReadMessage(context.Background())
			if err != nil {
				log.Fatalln(err)
			}
			fmt.Printf("message at topic:%v partition:%v offset:%v	%s = %s\n", m.Topic, m.Partition, m.Offset, string(m.Key), string(m.Value))
		}
	}()

	writer := getKafkaWriter(kafkaURL)
	defer writer.Close()

	wg.Add(1)
	go func() {
		defer wg.Done()

		fmt.Println("start publishing ... !!")

		for i := 0; i < 2; i++ {
			key := fmt.Sprintf("Key-%d", i)

			msg := kafka.Message{
				Topic:         topic,
				Key:           []byte(key),
				Value:         []byte(fmt.Sprint(uuid.NewV4())),
			}

			err := writer.WriteMessages(context.Background(), msg)
			if err != nil {
				fmt.Println(err)
			} else {
				fmt.Println("published", key)
			}

			time.Sleep(1 * time.Second)
		}
	}()


	wg.Wait()

	fmt.Println("all messages were published and consumed")
}

```

the output is the following

```
start publishing ... !!
start consuming ... !!
published Key-0
published Key-1

```

**Expected behavior**
The reader consumes the messages that the writer just published.
