### ISSUE TITLE
SASL Authentication Failed with EC2RoleProvider and aws_msk_iam.Mechanism

### ISSUE THREAD

**Issue by thadamski** [segmentio/kafka-go#832]
**Describe the bug**
SASL Authentication Failure when using `ec2rolecreds.EC2RoleProvider` with `aws_msk_iam.Mechanism`

Using `credentials.EnvProvider{}` works as expected using the example code below, but when removing the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` env. variables, authentication no longer works with the ec2Metadata credentials technique, using the role attached to the Pod running within our EKS cluster.

**Kafka Version**
AWS MSK 2.8.1

**To Reproduce**
- Create an MSK cluster with IAM authentication only
- Create a topic "quickstart-events" and publish some events to the topic
- Run the example code below and see the SASL error:

```
{"level":"error","error":"[58] SASL Authentication Failed: SASL Authentication failed","time":"2022-01-28T14:01:38Z","caller":"/go/src/github.com/my-org/my-project/main.go:51","message":"error while reading batch"}
```

Example consumer code using `kafka-go` and `sasl/aws_msk_iam`

```go
package main

import (
	"context"
	"crypto/tls"
	"github.com/aws/aws-sdk-go/aws/credentials"
	"github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds"
	"github.com/aws/aws-sdk-go/aws/ec2metadata"
	"github.com/aws/aws-sdk-go/aws/session"
	sigv4 "github.com/aws/aws-sdk-go/aws/signer/v4"
	"github.com/rs/zerolog/log"
	"github.com/segmentio/kafka-go"
	"github.com/segmentio/kafka-go/sasl/aws_msk_iam"
	"os"
	"strings"
	"time"
)

func main() {
	sess, err := session.NewSession()
	if err != nil {
		log.Logger.Fatal().Err(err)
	}
	awsCredentials := credentials.NewChainCredentials(
		[]credentials.Provider{
			&credentials.EnvProvider{},
			&ec2rolecreds.EC2RoleProvider{
				Client: ec2metadata.New(sess),
			},
		})

	kafkaDialer := &kafka.Dialer{
		Timeout:   10 * time.Second,
		DualStack: true,
		SASLMechanism: &aws_msk_iam.Mechanism{
			Signer: sigv4.NewSigner(awsCredentials),
			Region: os.Getenv("AWS_DEFAULT_REGION"),
		},
		TLS: &tls.Config{},
	}

	brokers := strings.Split(os.Getenv("KAFKA_SERVERS"), ",")
	topic := "quickstart-events"
	batchSize := int(10e6) // 10MB
	r := kafka.NewReader(kafka.ReaderConfig{
		Brokers:   brokers,
		Topic:     topic,
		Dialer:    kafkaDialer,
		Partition: 0,
		MinBytes:  batchSize,
		MaxBytes:  batchSize,
	})

	for {
		m, err := r.ReadMessage(context.Background())
		if err != nil {
			log.Logger.Err(err).Msg("error while reading batch") // <-- Error log from above
			break
		}
		log.Logger.Info().Msgf("Got Kafka Event %q", string(m.Value))
	}
}
```

**Expected behavior**
I would expect a successful authentication, and in the context of the example code, log the messages from the topic.

Using env. variables with the example code above, I get the following output of topic data:

```
{"level":"info","time":"2022-01-28T15:14:01Z","message":"Got Kafka Event \"foo\""}
{"level":"info","time":"2022-01-28T15:14:01Z","message":"Got Kafka Event \"bar\""}
{"level":"info","time":"2022-01-28T15:14:01Z","message":"Got Kafka Event \"baz\""}
{"level":"info","time":"2022-01-28T15:14:01Z","message":"Got Kafka Event \"bat\""}
{"level":"info","time":"2022-01-28T15:14:01Z","message":"Got Kafka Event \"bang\""}
```

**Additional context**

To verify the AWS role works as expected, and also that the k8s serviceAccount in use is hooked up correctly, a test Pod was created and successful consumption of events using the kafka-cli has been observe

Example k8s resources:

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "my-aws-role-arn"
  labels:
    app: kafka-cli
  name: kafka-cli
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-cli
  name: kafka-cli
spec:
  selector:
    matchLabels:
      app: kafka-cli
  template:
    metadata:
      labels:
        app: kafka-cli
    spec:
      containers:
        - command:
            - /bin/sh
            - -ec
            - sleep 10000
          image: openjdk:17.0.2-slim-bullseye
          name: kafka-cli
      serviceAccountName: kafka-cli
```

Exec onto the pod:

```shell
kubectl exec -it $(kubectl get pod -l app=kafka-cli -o name) -- bash
```

Install the kafka-cli, configure for IAM Auth, and consume events

```shell
kafka_server_list="redacted:9098,redacted-2:9098,redacted-3:9098" && \

cd / && \
apt update && apt install wget -y && \

# Install Kafka CLI
wget https://dlcdn.apache.org/kafka/2.8.1/kafka_2.13-2.8.1.tgz && \
tar -xzf kafka_2.13-2.8.1.tgz && \
ln -s ./kafka_2.13-2.8.1 kafka && \

# Install AWS MSK IAM Authenticator Jar into Classpath
cd /kafka/libs && \
wget https://github.com/aws/aws-msk-iam-auth/releases/download/v1.1.1/aws-msk-iam-auth-1.1.1-all.jar && \
cd / && \

# Configure to authenticate with IAM Role
echo "ssl.truststore.location=/usr/local/openjdk-17/lib/security/cacerts" >> /config.properties && \
echo "security.protocol=SASL_SSL" >> /config.properties && \
echo "sasl.mechanism=AWS_MSK_IAM" >> /config.properties && \
echo "sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;" >> /config.properties && \
echo "sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler" >> /config.properties && \

# Consume events
/kafka/bin/kafka-console-consumer.sh --topic quickstart-events --from-beginning --bootstrap-server ${kafka_server_list} --consumer.config /config.properties
```

Output:

```shell
# truncated output...

foo
bar
baz
bat
bang
```
