### ISSUE TITLE
How to create topic for Kafka cluster?

### ISSUE THREAD

**Issue by ielyanov** [segmentio/kafka-go#851]
Hello.
How connect to multiple brokers?

       conn, err := kafka.Dial("tcp", "kafka-0:9092,kafka-1:9072")
	if err != nil {
		panic(err.Error())
	}
	controller, _ := conn.Controller()
	fmt.Printf("%s %d ", controller.Host, controller.Port)
	conncontroller, err := kafka.Dial("tcp", net.JoinHostPort(controller.Host, strconv.Itoa(controller.Port)))
	if err != nil {
		panic(err.Error())
	}
	err = conncontroller.CreateTopics(topic)
	if err != nil {
		panic(err.Error())
	}
	
	
But I got error.

panic: dial tcp: lookup kafka-0:29092,kafka-1:29072: Try again
or
panic: dial tcp: lookup kafka-0:9092,kafka-1:9072: Try again

--

The client sometimes connect to the kafka-0:29092

I think the client can not connect to the kafka leader in docker.

----
docker-compose.yaml

```
version: '3'

volumes:
  zookeeper-data-0:
    driver: local
  zookeeper-log-0:
    driver: local
  kafka-data-0:
    driver: local
  kafka-data-1:
    driver: local
  kafka-data-2:
    driver: local

services:

    zookeeper:
      image: confluentinc/cp-zookeeper:7.0.1
      volumes:
        - zookeeper-data-0:/var/lib/zookeeper/data:Z
        - zookeeper-log-0:/var/lib/zookeeper/log:Z
      environment:
        ZOOKEEPER_CLIENT_PORT: '2181'
        ZOOKEEPER_ADMIN_ENABLE_SERVER: 'false'
      networks:
        - kafka-internal

    kafka-0:
      image: confluentinc/cp-kafka:7.0.1
      volumes:
        - kafka-data-0:/var/lib/kafka:Z
      #ports:
      #  - 9092:9092
      environment:
        KAFKA_BROKER_ID: '0'
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_NUM_PARTITIONS: '12'
        KAFKA_COMPRESSION_TYPE: 'snappy'
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '3'
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '3'
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '2'
        KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
        KAFKA_JMX_PORT: '9091'
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
        KAFKA_AUTHORIZER_CLASS_NAME: 'kafka.security.authorizer.AclAuthorizer'
        KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
        KAFKA_LISTENERS: 'INTERNAL://kafka-0:29092,EXTERNAL://kafka-0:9092'
        KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka-0:29092,EXTERNAL://localhost:9092'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
        KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      depends_on:
        - zookeeper
      networks:
        - kafka-internal


    kafka-1:
      image: confluentinc/cp-kafka:7.0.1
      volumes:
        - kafka-data-1:/var/lib/kafka:Z
      #ports:
      #  - 9082:9082
      environment:
        KAFKA_BROKER_ID: '1'
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_NUM_PARTITIONS: '12'
        KAFKA_COMPRESSION_TYPE: 'snappy'
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '3'
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '3'
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '2'
        KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
        KAFKA_JMX_PORT: '9081'
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
        KAFKA_AUTHORIZER_CLASS_NAME: 'kafka.security.authorizer.AclAuthorizer'
        KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
        KAFKA_LISTENERS: 'INTERNAL://kafka-1:29082,EXTERNAL://kafka-1:9082'
        KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka-1:29082,EXTERNAL://localhost:9082'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
        KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      depends_on:
        - zookeeper
      networks:
        - kafka-internal


    kafka-2:
      image: confluentinc/cp-kafka:7.0.1
      volumes:
        - kafka-data-2:/var/lib/kafka:Z
      #ports:
      #  - 9072:9072
      environment:
        KAFKA_BROKER_ID: '2'
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_NUM_PARTITIONS: '12'
        KAFKA_COMPRESSION_TYPE: 'snappy'
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '3'
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '3'
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '2'
        KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
        KAFKA_JMX_PORT: '9071'
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
        KAFKA_AUTHORIZER_CLASS_NAME: 'kafka.security.authorizer.AclAuthorizer'
        KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
        KAFKA_LISTENERS: 'INTERNAL://kafka-2:29072,EXTERNAL://kafka-2:9072'
        KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka-2:29072,EXTERNAL://localhost:9072'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
        KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      depends_on:
        - zookeeper
      networks:
        - kafka-internal


    client: #kafka client
        build:
            context: .
            dockerfile: ./client.dockerfile
        ports:
            - "8000:1323" #external port 8000
        environment:
            - TZ=Europe/Moscow
            - APP_ADDR=:1323
            - GO_ENV=dev
            - GOPATH=/go
        container_name: kafka-client
        depends_on:
          - kafka-0
          - kafka-1
          - kafka-2
        networks:
          - kafka-internal

networks:
    kafka-internal:
        driver: bridge
```
 
client.dockerfile

```
FROM golang:1.17-alpine3.13
WORKDIR /go/src
COPY ./app/ /go/src

ENV GOPATH "/go:/go"
RUN go env -w GO111MODULE=on
RUN go mod init apimobile
RUN go mod tidy

RUN go get -d -v ./...
ENV APP_ADDR ":1323"
ENV GO_ENV "dev"

EXPOSE 1323
ENTRYPOINT go run main.go
```
