### ISSUE TITLE
ConsumerGroup not reading from all listed topics 

### ISSUE THREAD

**Issue by terryosayawe-cpi** [segmentio/kafka-go#974]
**Describe the bug**

> I have created a consumer group to read from a list of topics, unfortunately it only reads from one topic in the list.

**Kafka Version**

> * What version(s) of Kafka are you testing against? confluentinc/cp-server:7.2.0
> * What version of kafka-go are you using? v0.4.34

**To Reproduce**

Create a consumer group with multiple topics
```
r := kafka.NewReader(
		kafka.ReaderConfig{
			Brokers:                []string{"broker:29092"},
			GroupID:                "cs-group-1",
			MinBytes:               10000
			MaxBytes:               20000000,
			GroupTopics:            []string{"topic_1", "topic_2","topic_3"},
			WatchPartitionChanges:  true,
			PartitionWatchInterval: time.Duration(5),
		},
	)
```

> Resources to reproduce the behavior:

```yaml
---
# docker-compose.yaml
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - default
    volumes:
      - "zookeeper_data:/var/lib/zookeeper/data"
      - "zookeeper_log:/var/lib/zookeeper/log"
  broker: #kafka server
    image: confluentinc/cp-server:7.2.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    networks:
      - default
    volumes:
      - "kafka_data:/var/lib/kafka/data"
  control-center: #kafka ui
    image: provectuslabs/kafka-ui:latest
    hostname: control-center
    container_name: control-center
    depends_on:
      - broker
    ports:
      - "9021:8080"
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'broker:29092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      KAFKA_CLUSTERS_0_NAME: "cp-local-telemetry"
      PORT: 9021
    networks:
      - default
...
```

```go
package main

import (
    "github.com/segmentio/kafka-go"
)

func main() {
    // Adding a fully reproducible example will help maintainers provide
    // assistance to debug the issues.
    ...
}
```

**Expected Behavior**

> Consumer group should read from all topics listed in GroupTopics 

**Observed Behavior** 

> ConsumerGroup only reads from one topic in the list 

```
Often times, pasting the logging output from a kafka.Reader or kafka.Writer will
provide useful details to help maintainers investigate the issue and provide a
fix. If possible, providing stack traces or CPU/memory profiles may also contain
valuable information to understand the conditions that triggered the issue.
```

**Additional Context**

> Add any other context about the problem here.
